### ISSUE TITLE
sim800l resets

### ISSUE THREAD

**Issue by thomasgr30** [AyushMarsian/SIM800L#2]
hello ,
when i try readServiceProvider.ino the module first resets, is there a way we can prevent that?
thank you

**Comment by ankitghevariya** [comment]
Hello @thomasgr30 ,

Well, I have seen in the library, this particular example is not calling GSM reset function, therefore I think there is some bug in your project.

I can help you with, but for that you should have to share some data with me.

I want, 
    1) Your schematic design
    2) Your code which you are using and observing reset condition
    3) Output or serial window screenshot in which you monitoring data and AT responses from GSM.
    4) Have you soldered the hardware or using on bread board ?
    5) What is the voltage on GSM, and power supply's current capacity ?

Regards,
AyushMarsian
(Ankit Ghevariya)

**Comment by ankitghevariya** [comment]
@thomasgr30 

I did not get any response from you, I am closing this issue.

Thank you

Regards,
AyushMarsian
(Ankit Ghevariya)
