### ISSUE TITLE
Esp8266 pin connections and use ?

### ISSUE THREAD

**Issue by denden4444** [AyushMarsian/SIM800L#3]
Hi there 

Do you possibly have some connection info when using an esp8266 nodeMCU ?

Thank you

**Comment by ankitghevariya** [comment]
Hi @denden4444 

What type of connection do you required ?

Do you want to connect GSM SIM800l With nodeMCU (ESP12E module) ? Or you want anything else ? 
Do you want to connect GSM on hardware serial port or you want to use any other pin of nodeMCU as software serial ?

Regards,
AyushMarsian
(Ankit Ghevariya)

**Comment by ankitghevariya** [comment]
@denden4444 

I didn't received any response from you, so I am closing this issue. If you face any problem you are most welcome, I will help you to fix it.
